
/**
* Annuaire.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* vendredi 4 avril 2014 01 h 26 CEST
*/

public interface Annuaire extends AnnuaireOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Annuaire
