
/**
* IcarreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* vendredi 4 avril 2014 00 h 09 CEST
*/

public interface IcarreOperations 
{
  void carre (int source, org.omg.CORBA.IntHolder resultat);
} // interface IcarreOperations
